# LIST OF ERRORS THAT MAY OCCUR WHILE USING THIS SERVICE
WEBSEARCH_BAD_TERM_FORMAT = -1221
WEBSEARCH_INVALID_SEARCHENGINE = -1222
WEBSEARCH_INVALID_NUMRESULTS = -1223
WEBSEARCH_INVALID_PROXY_FORMAT = -1224

WEBSEARCH_GOOGLE_ERROR = -1321
WEBSEARCH_BING_ERROR = -1322
WEBSEARCH_YAHOO_ERROR = -1323
WEBSEARCH_GENERAL_ERROR = -1325

WEBSEARCH_INVALID_PROXYLIST = -1341
WEBSEARCH_INVALID_PROXY_ERROR1 = -1331
WEBSEARCH_INVALID_PROXY_ERROR2 = -1332
WEBSEARCH_INVALID_PROXY_ERROR3 = -1333
WEBSEARCH_PROXY_NOT_WORKING = -1334
WEBSEARCH_PROXY_TEST_FAILED = -1335
WEBSEARCH_DOSEARCH_ERROR = -1326
WEBSEARCH_SEARCH_URL_ERROR = -1201
WEBSEARCH_GENERAL_REQUEST_ERROR = -1202
WEBSEARCH_SEARCH_SCRAPING_ERROR = -1203
WEBSEARCH_SEARCH_CAPTCHA_ERROR = -1204
WEBSEARCH_SEARCH_FETCH_URLS_ERROR = -1301
WEBSEARCH_CONNEXION_ERROR = -1370

SERVICE_INVALID_REQUEST_FORMAT = 800
SERVICE_UNKNOWN_ERROR = 850

errors = {

    WEBSEARCH_BAD_TERM_FORMAT: "WEBSEARCH_BAD_TERM_FORMAT",
    WEBSEARCH_INVALID_SEARCHENGINE: "WEBSEARCH_INVALID_SEARCHENGINE",
    WEBSEARCH_INVALID_NUMRESULTS: "WEBSEARCH_INVALID_NUMRESULTS",
    WEBSEARCH_INVALID_PROXY_FORMAT: "WEBSEARCH_INVALID_PROXY_FORMAT",

    WEBSEARCH_GOOGLE_ERROR: "WEBSEARCH_GOOGLE_ERROR",
    WEBSEARCH_BING_ERROR: "WEBSEARCH_BING_ERROR",
    WEBSEARCH_YAHOO_ERROR: "WEBSEARCH_YAHOO_ERROR",
    WEBSEARCH_GENERAL_ERROR: "WEBSEARCH_GENERAL_ERROR",

    WEBSEARCH_INVALID_PROXYLIST: "WEBSEARCH_INVALID_PROXYLIST",
    WEBSEARCH_INVALID_PROXY_ERROR1: "WEBSEARCH_INVALID_PROXY_ERROR1",
    WEBSEARCH_INVALID_PROXY_ERROR2: "WEBSEARCH_INVALID_PROXY_ERROR2",
    WEBSEARCH_INVALID_PROXY_ERROR3: "WEBSEARCH_INVALID_PROXY_ERROR3",
    WEBSEARCH_PROXY_NOT_WORKING: "WEBSEARCH_PROXY_NOT_WORKING",
    WEBSEARCH_PROXY_TEST_FAILED: "WEBSEARCH_PROXY_TEST_FAILED",
    WEBSEARCH_DOSEARCH_ERROR: "WEBSEARCH_DOSEARCH_ERROR",
    WEBSEARCH_SEARCH_URL_ERROR: "WEBSEARCH_SEARCH_URL_ERROR",
    WEBSEARCH_GENERAL_REQUEST_ERROR: "WEBSEARCH_GENERAL_REQUEST_ERROR",
    WEBSEARCH_SEARCH_SCRAPING_ERROR: "WEBSEARCH_SEARCH_SCRAPING_ERROR",
    WEBSEARCH_SEARCH_CAPTCHA_ERROR: "WEBSEARCH_SEARCH_CAPTCHA_ERROR",
    WEBSEARCH_SEARCH_FETCH_URLS_ERROR: "WEBSEARCH_SEARCH_FETCH_URLS_ERROR",
    WEBSEARCH_CONNEXION_ERROR: "WEBSEARCH_CONNEXION_ERROR",

    SERVICE_INVALID_REQUEST_FORMAT: "SERVICE_INVALID_REQUEST_FORMAT",
    SERVICE_UNKNOWN_ERROR: "SERVICE_UNKNOWN_ERROR",
}
